### ISSUE TITLE
Let kids opt to turn constellation figures on/off?

### ISSUE THREAD

**Issue by patudom** [wwt-ambassadors/testbed#34]
Shawn says the kids will likely not be able to pick out the constellation Orion, so I'm wondering if it would be helpful to let kids have the option of turning on constellation figures to help orient them in the sky. (We wouldn't want them on all the time because they will block some of the stars we want them to look at).

So keep that in mind, @heywooddogwood, as you design the layout - we might want space for this extra button.  Thanks!

<img width="1274" alt="Screen Shot 2020-04-02 at 4 00 26 PM" src="https://user-images.githubusercontent.com/12750048/78296219-55018e00-74fb-11ea-9712-b6fa16820fbc.png">

**Comment by heywooddogwood** [comment]
You created this constellation feature and it's working great, so I'm going to close out this issue.
